name: .NET Docs
on:
  release:
    types:
      - published
  workflow_dispatch:
  push:
    paths:
      - ".editorconfig"
      - ".gitignore"
      - ".gitmodules"
      - "docs/**"
      - "examples/**"
      - "libs/**"
      - "res/**"
      - "src/**"
      - "tests/**"
      - "tools/**"

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
permissions:
  contents: write

jobs:
  build:
    name: "Build Docs"
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.103
      - name: Install DocFX
        run: dotnet tool install -g docfx
        continue-on-error: true
      - name: Build documentation
        run: docfx docs/docfx.json
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Path of the directory containing the static assets.
          path: ./docs/_site/ # default is _site/
  deploy:
    name: "Deploy Docs"
    needs: build
    runs-on: self-hosted
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment, originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
    environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}