name: Publish Release
on:
  release:
    types: ["published"]

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

jobs:
  nuget-release:
    name: Nuget Release
    runs-on: ubuntu-latest
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7
      - name: Nuget Packages
        run: |
          mkdir build
          dotnet pack -c Release -o build -p:Version=${{ github.event.release.tag_name }}
          dotnet nuget push "build/*" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
      - name: Upload Nuget Packages To Github Actions
        uses: actions/upload-artifact@v3
        with:
          name: OoLunar.DSharpPlus.CommandAll-${{ github.event.release.tag_name }}.zip
          path: build/*
      - name: Upload Nuget Packages To Github Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: build/*
          token: ${{ secrets.GITHUB_TOKEN }}
          omitNameDuringUpdate: true # We don't want to update the name of the release.
          omitBodyDuringUpdate: true # We don't want to update the body of the release.
